// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDneLEcFVl5k7CAO0O9L-dw6X5lU6C07Ko',
    appId: '1:88398717416:web:5e8a291152ecf174af045d',
    messagingSenderId: '88398717416',
    projectId: 'chitan160204',
    authDomain: 'chitan160204.firebaseapp.com',
    storageBucket: 'chitan160204.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDneLEcFVl5k7CAO0O9L-dw6X5lU6C07Ko',
    appId: '1:88398717416:android:5e8a291152ecf174af045d',
    messagingSenderId: '88398717416',
    projectId: 'chitan160204',
    storageBucket: 'chitan160204.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDneLEcFVl5k7CAO0O9L-dw6X5lU6C07Ko',
    appId: '1:88398717416:ios:5e8a291152ecf174af045d',
    messagingSenderId: '88398717416',
    projectId: 'chitan160204',
    storageBucket: 'chitan160204.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDneLEcFVl5k7CAO0O9L-dw6X5lU6C07Ko',
    appId: '1:88398717416:macos:5e8a291152ecf174af045d',
    messagingSenderId: '88398717416',
    projectId: 'chitan160204',
    storageBucket: 'chitan160204.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDneLEcFVl5k7CAO0O9L-dw6X5lU6C07Ko',
    appId: '1:88398717416:windows:5e8a291152ecf174af045d',
    messagingSenderId: '88398717416',
    projectId: 'chitan160204',
    storageBucket: 'chitan160204.firebasestorage.app',
  );
}
